### ISSUE TITLE
Does not work with underlined syntax

### ISSUE THREAD

**Issue by Nex-Otaku** [skoropadas/telegramify-markdown#1]
This is Markdown for underlined text:

`__Underlined__`

This is what I get after running it with telegramifyMarkdown:

` *Underlined* `

Note the spaces here, converter replaces underscores with stars and adds spaces for some reason.

**Comment by skoropadas** [comment]
@Nex-Otaku Yeah, now I see, I looked in more detail, as I understood, you want to use a double underscore, and when converting, get it the same.

But there is only one problem, in a Native Markdown, double underlining means bold text, but in the Telegram Markdown, it means underlined text, so we can't convert it directly.
