### ISSUE TITLE
List markers causes all subsequent characters to be incorrectly escaped

### ISSUE THREAD

**Issue by RainEggplant** [skoropadas/telegramify-markdown#3]
**Describe the bug**
The list markers (`-`, `*` for unordered lists and `1.`, `2.` for ordered lists) causes all subsequent characters to be incorrectly escaped.

**To Reproduce**
Convert the following text:

```
- To make text **bold**, surround it with double asterisks (`**`): `**This text is bold.**`
```

**Expected behavior**

The expected result should be:

```
•   To make text *bold*, surround it with double asterisks \(`**`\): `**This text is bold.**`
```

**Current behavior**

```
•   To make text \*bold\*, surround it with double asterisks \\(\`\*\*\`\\): \`\*\*This text is bold\.\*\*\`
```

**Comment by skoropadas** [comment]
Yes, sorry, I did it with the last fix, new version with fix is building

**Comment by RainEggplant** [comment]
Thanks! It's working now ❤️
