### ISSUE TITLE
replaceAll is not a function

### ISSUE THREAD

**Issue by Azarel19** [skoropadas/telegramify-markdown#6]
**Describe the bug**
Good day, a problem arises during the release of my TypeScript library. At the final step of the release, the semantic-release-telegram-bot plugin is called, but the call ends with an error: "TypeError: unified(...).use(...).use(...).use(...).use(...).use(...).use(...).processSync(...).toString(...).replaceAll is not a function". Most likely the issue is that in my project I'm using node.js 14 and in the tsconfig.json file, the "target" parameter is set to "es2015". I can't upgrade to newer versions due to support for legacy code. I would like to request either to replace the method replaceAll with replace or to add a polyfill to support the old code.

**To Reproduce**
To reproduce, you will need to use node.js 14 for project building and set a target parameter value lower than "es2021" in the tsconfig.json file.

**Expected behavior**
There have been no issues with methods that were recently added to the ECMAScript standard and are used in your library.

**Screenshots**
<img width="777" alt="Screenshot_50" src="https://github.com/skoropadas/telegramify-markdown/assets/17447366/58cea9b0-458d-4dc2-80bf-06bddd82cb79">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 122.0.6261.71

**Comment by skoropadas** [comment]
Hi, no problem I'll fix it
