### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by sharpvik** [skoropadas/telegramify-markdown#9]
**Describe the solution you'd like**

It'd be really nice if you could support TS.

**Describe alternatives you've considered**

There are two ways you can go about it (afaik):

1. Simply create a declaration file (and since your module exports just one function, this should be fairly simple).
2. (Gradually) rewrite the library using TS -- this would improve type safety if this is something you care about.

**Additionally**

There are forks to your library that already have TS support. Perhaps, you could consider simply ingesting their code.

**Comment by sharpvik** [comment]
As a side note, your library works wonders! Thank you very much!

**Comment by skoropadas** [comment]
Sure no problem, I will add a declaration file, I just don't think that rewriting the whole library using typescript makes sense since it exports only one function
